### ISSUE TITLE
Outputs not being written

### ISSUE THREAD

**Issue by AbhijitSridhar** [Cartucho/OpenLabeling#40] opened 2019-01-26 12:50 UTC
My output files are still blank even after performing labelling. When I restart the program, on the gui I can still see my old labels, however the corresponding text files are empty

**Comment by vuthede** [comment] 2019-01-27 03:57
It is so weird. My corresponding text files are not empty like yours. 
I think It  may be a minor bug of the code, which sometimes cause problem in case someone use different version of opencv or environment (Linux, Window.). I use opencv 4.0 and Linux.

**Comment by AbhijitSridhar** [comment] 2019-01-27 04:02
I use opencv3 and Linux. My problem is that some of the text files are being written, while the majority are left blank. I labelled around 500 images yesterday only to find out later that only around 10-20 have the proper data in the text file. All the others are empty

**Comment by Cartucho** [comment] 2019-01-27 12:33
@vuthede I am also curious. In my computer seems to work fine, but probably there is a bug.

**Comment by vuthede** [comment] 2019-01-27 12:42
yeah @Cartucho , In my computer, it seems work fine too, I think there may some cases that the code did not cover.

**Comment by AbhijitSridhar** [comment] 2019-01-31 03:44
Okay so I'm using python 3.6 and opencv 3.3. So I reduced my number of classes from 5 to 2 and now it works with no problem.
Another thing I noticed is when I was trying to label for 5 classes, the only files being written were 0,1,10,100,1000,1001.txt Not sure if this is an indicator of the problem or something else

**Comment by Cartucho** [comment] 2019-02-01 17:08
`0,1,10,100,1000,1001.txt` ohhhhh this explains a lot! I think the problem is with the name of your images.

The images are sorted so 0, 1, 10, 100 is how python will sort your files by the standard. I changed the sorting to what's called `natural_sort` a more human-like sorting. Please give it a try.

If this is the case you indeed labeled the images, you were just opening the wrong files.

**Comment by Cartucho** [comment] 2019-02-10 17:28
@AbhijitSridhar could you please confirm that it is working now?

**Comment by AbhijitSridhar** [comment] 2019-02-14 11:42
It works perfectly for two classes. When I first tried, I had 5-6 classes and faced this issue. I didn't change the file naming convention when trying for two classes

**Comment by Cartucho** [comment] 2019-03-29 09:04
Hello @AbhijitSridhar can I close this issue? I think I solved it

**Closed** 2019-04-11 08:45 UTC
